version: '2'
services:
  simpleservice:
    image: namelosw/simpleservice:latest
    ports:
      - "8080:8080"
  configurationserver:
    image: namelosw/configurationserver
    ports:
      - "8888:8888"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "main"
  licensingservice:
    image: namelosw/licensingservice:latest
    ports:
      - "8081:8080"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
